### PR TITLE
packetbeat: format uid/gid to mubers without comma

### PR DESCRIPTION
**Pull request by kofemann**
it's better to display uid as 1000 instead of 1,000

before:
screenshot from 2016-04-15 21-59-08

after:
screenshot from 2016-04-15 21-57-37

### CODE REVIEW

**Comment by monicasarbu** [comment]
@kofemann Thank you for the PR.

**Comment by monicasarbu** [comment]
Starting with 5.0.0-alpha2, beats-dashboards repo is deprecated as all the dashboards are in the repository of each beat. This feature needs to be added to the beats repo as well.

**Comment by kofemann** [comment]
@monicasarbu I can see that new repo is missing all NFS staff. shall I add it as into old repository or there is a 'official' procedure for that?

**Comment by monicasarbu** [comment]
@kofemann Yes, I didn't migrate yet the NFS dashboard to the beats repository, but I just created a pull request to add the NFS dashboard together with all the dependencies to the beats repository. Please let me know if I miss something: https://github.com/elastic/beats/pull/1424

**Pull request merged**
