### PR TITLE
packetbeat: add dashboard to visualize NFS traffic

### PR DESCRIPTION
**Pull request by kofemann**
Signed-off-by: Tigran Mkrtchyan tigran.mkrtchyan@desy.de

### CODE REVIEW

**Comment by kofemann** [comment]
The screenshot of the dashboard.

screenshot from 2016-03-31 17-44-37

shall I add it into screenshots directory and update README file as well?

**Comment by monicasarbu** [comment]
@kofemann yes, please add it to the screenshots directory.

**Comment by monicasarbu** [comment]
Ah, great. The screenshot is already there!

**Comment by monicasarbu** [comment]
@kofemann Thank you for creating a dashboard as well.

**Pull request merged**
