### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by dovicn**
I have updated some file names to allow for windows file system support so the repo can be cloned in a windows environment, this mean the index names needed to be sourced from the title json attribute rather than the filename. I have also added a load.ps1 powershell script to do the equivalent of the existing load.sh bash script.

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Would be good if @monicasarbu could also have a look.

@andrewkroh Can you have a look at the Powershell script?

**Comment by andrewkroh** [comment]
LGTM

@dovicn  Thanks!

**Comment by andrewkroh** [comment]
@dovicn Can you please update the PR to resolve the conflict that Github is complaining about. Thanks

**Comment by dovicn** [comment]
@andrewkroh I have resolved conflicts and signed CLA.

**Pull request merged**
