### PR TITLE
Add ability to specify custom kibana index

### PR DESCRIPTION
**Pull request by KarolisL**
We use custom indices to store kibana configuration. This PR adds support to specify it.

### CODE REVIEW

**Comment by ruflin** [comment]
@KarolisL Would you mind signing the CLA? https://www.elastic.co/contributor-agreement/

**Comment by KarolisL** [comment]
I believe I did that few moments ago. Could you please confirm that I did it correctly?

**Comment by ruflin** [comment]
I checked manually and all looks good. Normally it updates the check after a comment but probably you were too fast.

**Comment by ruflin** [comment]
@KarolisL Merged. Thanks.

**Pull request merged**
