### PR TITLE
Change release.sh to make a zip file

### PR DESCRIPTION
**Pull request by andrewkroh**
This will need a backport to 1.1.0.

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Should we also update this line? https://github.com/elastic/beats-dashboards/blob/2f04f04126beae8e82ce8aa74b652f35ed21d709/Makefile#L5

**Comment by andrewkroh** [comment]
It looks like I should delete `release.sh` and update the Makefile (which I didn't see). I will fix this.

**Comment by andrewkroh** [comment]
Fixed. I removed the old `release.sh` and changed the Makefile to generate a `zip` instead of `tar.gz`.

**Comment by tsg** [comment]
LGTM.

**Comment by dedemorton** [comment]
@andrewkroh I want to make sure I get the timing of the doc updates right. Will the zip version of the load script be available when 1.1 officially releases? Waiting to push the doc updates until I know for sure...

**Comment by andrewkroh** [comment]
Yes, the beats dashboard zip file for 1.1 we be released at the same time. This PR does need back-ported yet.

**Pull request merged**
