### PR TITLE
update index pattern convention

### PR DESCRIPTION
**Pull request by lmangani**
Patch proposal for testing (missing data to fully validate each index) addressing https://github.com/elastic/beats-dashboards/issues/36 and minor user req.  https://github.com/elastic/beats-dashboards/issues/38

### CODE REVIEW

**Comment by tsg** [comment]
Thanks @lmangani, will check it tomorrow.

**Comment by monicasarbu** [comment]
@tsg I can take care of this PR.

**Comment by lmangani** [comment]
Fixed recurring pcre-fu glitches

**Comment by ruflin** [comment]
@lmangani Could you squash the commits?

**Comment by lmangani** [comment]
ACK

**Comment by ruflin** [comment]
@lmangani As I saw you merged in master, not sure if there was a misunderstanding. As you have made lots of small commits and some fixes I wanted to ask if you feel comfortable to squash the commits into 1 single commit?

**Comment by lmangani** [comment]
Let me close and re-PR clean

**Pull request closed without merging**
