### PR TITLE
Use auto timestamp in all widgets from the Topbeat dashboard

### PR DESCRIPTION
**Pull request by monicasarbu**

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. What is the `\"customInterval\":\"2h\"` for?

**Comment by monicasarbu** [comment]
It's just the default and you can configure it in Kibana. 
screen shot 2015-11-23 at 2 51 38 pm

**Comment by monicasarbu** [comment]
I am testing it at the moment. I hope to get merged in GA as indeed it's much better when using auto timestamp. Thanks @ruflin for the catch!

**Comment by ruflin** [comment]
@monicasarbu But we should use auto here too?

**Comment by monicasarbu** [comment]
I think the idea here is to have an interval and as it is "custom" you cannot set it to auto.

**Comment by monicasarbu** [comment]
It seems to work fine with the new visualizations. 

topbeat dashboard timestamp auto

**Comment by monicasarbu** [comment]
@tsg can we please merge these changes to 1.0.0 branch? Many thanks!

**Comment by ruflin** [comment]
LGTM

**Pull request merged**
