### PR TITLE
Update usage examples in load.sh

### PR DESCRIPTION
**Pull request by monicasarbu**
Fixes issue: https://github.com/elastic/beats-dashboards/issues/80

### CODE REVIEW

**Comment by monicasarbu** [comment]
@dedemorton could you please update the docs with more usage examples, similar with those that I added in this PR? Thanks!

**Comment by dedemorton** [comment]
@monicasarbu Are the examples in this section not sufficient? https://www.elastic.co/guide/en/beats/libbeat/1.1/getting-started.html#dashboard-load-options

Are you thinking that maybe I should show the full command line for each of the examples?

**Comment by monicasarbu** [comment]
@dedemorton I was thinking to add the following:

<pre>
load.sh -url http://test.com:9200
load.sh -url http://test.com:9200 -index .kibana_env
</pre>

maybe with the explanations:
1. you can specify the ES url where to load the dashboards
2. you can specify the kibana index pattern where to load the dashboards in ES

There are a few ways to pass in the password.

<pre>
load.sh -url https://xyz.found.io -u admin:pass
load.sh -url https://xyz.found.io -u admin:$(cat ~/pass-file) 
load.sh -url https://user:pass@xyz.found.io 
</pre>

with the explanations:
1. use file to not pollute bash history with password
2. just put user and pass in the url

(cc @andrewkroh )

**Comment by dedemorton** [comment]
@monicasarbu Are you saying that you want me to remove the section called "Dashboard Load Options" that shows all the command line options and replace it with something similar to what you say above, or do you want me to work the above info into the section called "Dashboard Load Options"? I decided to create a separate section because the info about load options  was getting lost after the Windows instructions.

**Comment by ruflin** [comment]
LGTM

**Pull request merged**
